# Generated by Django 6.0.4 on 2026-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название доставки')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('min_days', models.PositiveIntegerField(verbose_name='Мин срок дней')),
                ('max_days', models.PositiveIntegerField(verbose_name='Макс срок дней')),
                ('available_worldwide', models.BooleanField(default=False, verbose_name='Доступно по всему миру')),
                ('active', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ['price'],
            },
        ),
    ]
